// -*- C++ -*-
//
// generated by wxGlade 0.9.0a1 on Sun Apr 28 10:39:17 2019
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef MAINWINDOWLAYOUT_H
#define MAINWINDOWLAYOUT_H

#include <wx/wx.h>
#include <wx/image.h>

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode
#include "wxCustomButton.h"
// end wxGlade


class MainWindowLayout: public wxFrame {
public:
    // begin wxGlade: MainWindowLayout::ids
    // end wxGlade

    MainWindowLayout(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);

private:
    // begin wxGlade: MainWindowLayout::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: MainWindowLayout::attributes
    wxButton* button_3;
    wxButton* button_4;
    wxButton* button_5;
    wxButton* button_6;
    wxCustomButton* window_1;
    // end wxGlade
}; // wxGlade: end class


#endif // MAINWINDOWLAYOUT_H
