// -*- C++ -*-
//
// generated by wxGlade 0.9.6 on Wed Sep  9 14:52:01 2020
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#include <wx/wx.h>
#include "MainWindowLayout.h"

// begin wxGlade: ::extracode
// end wxGlade


MainWindowLayout::MainWindowLayout(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxFrame(parent, id, title, pos, size, wxDEFAULT_FRAME_STYLE)
{
    // begin wxGlade: MainWindowLayout::MainWindowLayout
    SetSize(wxSize(561, 404));
    mainWindow0_menubar = new wxMenuBar();
    wxMenu *wxglade_tmp_menu;
    wxglade_tmp_menu = new wxMenu();
    mainWindow0_menubar->Append(wxglade_tmp_menu, wxT("item"));
    SetMenuBar(mainWindow0_menubar);
    button_3 = new wxButton(this, wxID_ANY, wxT("button_3"));
    button_4 = new wxButton(this, wxID_ANY, wxT("button_4"));
    button_5 = new wxButton(this, wxID_ANY, wxT("button_5"));
    button_6 = new wxButton(this, wxID_ANY, wxT("button_6"));
    imagePanel = new ImagePanel(this, "nisse");

    set_properties();
    do_layout();
    // end wxGlade
}


void MainWindowLayout::set_properties()
{
    // begin wxGlade: MainWindowLayout::set_properties
    SetTitle(wxT("frame"));
    // end wxGlade
}


void MainWindowLayout::do_layout()
{
    // begin wxGlade: MainWindowLayout::do_layout
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_2 = new wxBoxSizer(wxVERTICAL);
    sizer_2->Add(button_3, 0, 0, 0);
    sizer_2->Add(button_4, 0, 0, 0);
    sizer_2->Add(button_5, 0, 0, 0);
    sizer_2->Add(button_6, 0, 0, 0);
    sizer_1->Add(sizer_2, 0, wxALL|wxEXPAND, 0);
    sizer_1->Add(imagePanel, 1, wxEXPAND, 0);
    SetSizer(sizer_1);
    Layout();
    // end wxGlade
}

