// -*- C++ -*-
//
// generated by wxGlade 0.8.3 on Sat Aug 11 20:59:08 2018
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

// This is an automatically generated file.
// Manual changes will be overwritten without warning!

#include <vector>
#include <string>
#include <wx/wx.h>
#include <wx/image.h>
#include "MainWindow.h"


class MyApp: public wxApp {
public:
    bool OnInit();
};

IMPLEMENT_APP(MyApp)

bool MyApp::OnInit()
{
	std::vector<std::string> args;
	for (int i = 1; i < wxApp::argc; i++) {
		args.push_back(std::string(wxApp::argv[i]));
	}

	wxInitAllImageHandlers();
	MainWindow* mainWindow0 = new MainWindow(NULL, wxID_ANY, wxEmptyString);
	SetTopWindow(mainWindow0);
	mainWindow0->Show();
	if (args.size() > 0) {
		mainWindow0->open(args.at(0));
	}
	return true;
}
