// -*- C++ -*-
//
// generated by wxGlade
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#include <wx/wx.h>
#include "AboutDialog.h"

// begin wxGlade: ::extracode
// end wxGlade


AboutDialog::AboutDialog(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
				wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE)
{
				// begin wxGlade: AboutDialog::AboutDialog
				SetSize(wxSize(434, 326));
				wxBoxSizer* sizer_1 = new wxBoxSizer(wxVERTICAL);
				panel_1 = new wxPanel(this, wxID_ANY);
				sizer_1->Add(panel_1, 0, wxEXPAND, 0);
				titleLabel = new wxStaticText(this, wxID_ANY, wxT("wxPic"));
				wxFont font = titleLabel->GetFont();
				font.SetWeight(wxFONTWEIGHT_BOLD);
				titleLabel->SetFont(font);
				sizer_1->Add(titleLabel, 0, wxALIGN_CENTER_HORIZONTAL, 0);
				versionLabel = new wxStaticText(this, wxID_ANY, wxT("version"));
				versionLabel->SetLabelText("Commit: " + Version::getVcsRef() + "\nBuild: " + Version::getBuildTimestamp());
				sizer_1->Add(versionLabel, 0, wxALIGN_CENTER_HORIZONTAL, 0);
				projectHyperlink = new wxHyperlinkCtrl(this, wxID_ANY, wxEmptyString, wxT("https://github.com/foolo/wxpic"));
				sizer_1->Add(projectHyperlink, 0, wxALIGN_CENTER_HORIZONTAL, 0);
				panel_2 = new wxPanel(this, wxID_ANY);
				sizer_1->Add(panel_2, 1, wxEXPAND, 0);
				wxBoxSizer* sizer_2 = new wxBoxSizer(wxHORIZONTAL);
				sizer_1->Add(sizer_2, 0, wxALIGN_RIGHT|wxALL, 4);
				button_OK = new wxButton(this, wxID_OK, wxEmptyString);
				button_OK->SetDefault();
				sizer_2->Add(button_OK, 0, 0, 0);
				
				SetSizer(sizer_1);
				SetAffirmativeId(button_OK->GetId());
				
				Layout();
				// end wxGlade
}

