// -*- C++ -*-
//
// generated by wxGlade
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#include <wx/wx.h>
#include "AboutDialog.h"

// begin wxGlade: ::extracode
// end wxGlade


AboutDialog::AboutDialog(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
				wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE)
{
				// begin wxGlade: AboutDialog::AboutDialog
				SetSize(wxSize(393, 208));
				wxBoxSizer* sizer_1 = new wxBoxSizer(wxHORIZONTAL);
				wxStaticText* label_1 = new wxStaticText(this, wxID_ANY, wxT("🛈"), wxDefaultPosition, wxDefaultSize, wxALIGN_CENTER_HORIZONTAL);
				label_1->SetFont(wxFont(28, wxFONTFAMILY_DEFAULT, wxFONTSTYLE_NORMAL, wxFONTWEIGHT_NORMAL, 0, wxT("")));
				sizer_1->Add(label_1, 2, 0, 0);
wxBoxSizer* sizer_3 = new wxBoxSizer(wxVERTICAL);
sizer_1->Add(sizer_3, 5, wxEXPAND, 0);
panel_1 = new wxPanel(this, wxID_ANY);
sizer_3->Add(panel_1, 0, wxEXPAND, 0);
				titleLabel = new wxStaticText(this, wxID_ANY, wxT("appname"));
				wxFont font = titleLabel->GetFont();
				font.SetWeight(wxFONTWEIGHT_BOLD);
				titleLabel->SetFont(font);
				titleLabel->SetLabelText(Version::getAppName() + " " + Version::getVersion());
				sizer_3->Add(titleLabel, 0, wxEXPAND, 0);
				versionLabel = new wxStaticText(this, wxID_ANY, wxT("version"));
				versionLabel->SetLabelText("Commit: " + Version::getVcsRef() + "\nBuild: " + Version::getBuildTimestamp());
    sizer_3->Add(versionLabel, 0, wxEXPAND, 0);
    projectHyperlink = new wxHyperlinkCtrl(this, wxID_ANY, wxEmptyString, wxT("https://github.com/wxpic.git"));
    sizer_3->Add(projectHyperlink, 0, 0, 0);
    panel_2 = new wxPanel(this, wxID_ANY);
    sizer_3->Add(panel_2, 1, wxEXPAND, 0);
    thankYouLabel = new wxStaticText(this, wxID_ANY, wxT("Thank you for using wxPic!"));
    wxFont thankYouFont = thankYouLabel->GetFont();
    				thankYouFont.SetWeight(wxFONTWEIGHT_NORMAL);
    				thankYouLabel->SetFont(thankYouFont);
    				sizer_3->Add(thankYouLabel, 0, wxEXPAND, 0);
    				wxBoxSizer* sizer_2 = new wxBoxSizer(wxHORIZONTAL);
    				sizer_3->Add(sizer_2, 0, wxALIGN_RIGHT|wxALL, 4);
    				button_OK = new wxButton(this, wxID_OK, wxEmptyString);
				button_OK->SetDefault();
				sizer_2->Add(button_OK, 0, 0, 0);
				
				SetSizer(sizer_1);
				SetAffirmativeId(button_OK->GetId());
				
				Layout();
				// end wxGlade
}

