// -*- C++ -*-
//
// generated by wxGlade
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef ABOUTDIALOG_H
#define ABOUTDIALOG_H

#include <wx/wx.h>
#include <wx/image.h>

// begin wxGlade: ::dependencies
#include <wx/hyperlink.h>
// end wxGlade

// begin wxGlade: ::extracode
#include "Version.h"
// end wxGlade


class AboutDialog: public wxDialog {
public:
				// begin wxGlade: AboutDialog::ids
				// end wxGlade

				AboutDialog(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:

protected:
    // begin wxGlade: AboutDialog::attributes
    wxPanel* panel_1;
    wxStaticText* titleLabel;
    wxStaticText* versionLabel;
    wxStaticText* thankYouLabel;
    wxHyperlinkCtrl* projectHyperlink;
    wxPanel* panel_2;
    wxButton* button_OK;
    // end wxGlade
}; // wxGlade: end class


#endif // ABOUTDIALOG_H
