name: wxpic
base: core18
version: '0.1'
summary: Example summary
description: Example description
grade: devel
confinement: devmode

apps:
  wxpic:
    extensions: [gnome-3-28]
    command: bin/wxpic

parts:
  # The wxWidgets SDK Stage Snaps
  # https://forum.snapcraft.io/t/the-wxwidgets-sdk-stage-snaps/10877
  wxwidgets-sdk:
    plugin: nil
    stage-snaps:
    - wxwidgets-sdk-gtk3
    filesets:
      crash-dialog-support:
      - usr/bin/*addr2line
      library-shared:
      - '**/lib/**/*.so*'
    prime:
    - $crash-dialog-support
    - $library-shared
  my-part:
    source: .
    plugin: meson
    after:
    - wxwidgets-sdk
    build-packages:
    - libgtk-3-dev
    stage-packages:
    - libwxgtk3.0-gtk3-0v5
    - libgdk-pixbuf2.0-0
